class ACBridge:
    def connect(self) -> None: ...
    def latest_obs(self) -> tuple[np.ndarray, dict]: ...
    def apply_action(self, steer: float, throttle: float, brake: float) -> None: ...
    def reset(self) -> None: ...